### ISSUE TITLE
ECB is not controlled by governments

### ISSUE THREAD

**Issue by robster7674** [monerobook/monerobook#103]
Under 1.1 it's mentioned that the ECB is controlled by governments. It's not, it's controlled by the central banks of the member states, see https://www.ecb.europa.eu/explainers/tell-me/html/who-owns-the-ecb.en.html:

"Together, the central banks of all the countries in the EU own the ECB. You could think of them as shareholders."

Since we know that all central banks are privately-owned entities, it follows that the ECB is also (indirectly) privately owned.

**Comment by serhack** [comment]
Thanks for the feedback.

> all central banks are privately-owned entities

I disagree, the term "central banks" does not implicates privately-owned entities. The major European central banks ([Italy](https://www.bancaditalia.it/chi-siamo/), [France](https://www.banque-france.fr/en/banque-de-france/about-banque-de-france/institutional-framework), [Deutsch](https://d-nb.info/1138787981/34)) are 100% owned by State, and thus are public entities. Although you can find that few central banks accepts joining of private companies, they act only as observer and they can not make critical decision in terms of coin emission. 

From the link you posted:
> These central banks are the only owners of the ECB – **we don’t have any private owners**. Among other things, this means that we are not influenced by private financial interests that might affect our independence.

**Comment by robster7674** [comment]
You're right, I should have written: "privately controlled" entitities. Ownership indeed does not tell us anything about control. There are many central banks that on paper (law) are owned by the relevant state, but if you dig deeper into the legislature, you will see language used to obfuscate who really controls these entities. This is about control, not ownership.

**Comment by robster7674** [comment]
Some background on central banks in general, fed specific:
https://www.corbettreport.com/federalreserve/
https://archive.org/details/pdfy--Pori1NL6fKm2SnY
