### ISSUE TITLE
Chapter 5 examples

### ISSUE THREAD

**Issue by xmrhaelan** [monerobook/monerobook#12]
At the end of Chapter 5, I think it would be great to name a few examples of other things that have been done:
> Over 200 contributors in the past year have contributed to Monero codebase (that includes the Monero “core”) and over 500 users have created **_their little (delete)_** Monero related project _**s, ranging from online payment and wallet services, usability and adoption, and even artwork and merchandise that have contributed to the cultural fabric of the Monero community.**_

**Comment by serhack** [comment]
Committed the change.
