### ISSUE TITLE
Chapter "Getting Started" VS Chapter "How Monero works". 

### ISSUE THREAD

**Issue by serhack** [monerobook/monerobook#28]
Hello,
I'm opening this issue in order to start a discussion about moving the chapter "How Monero works" from the 3rd chapter to the 2nd chapter.

@QuickBASIC

**Comment by serhack** [comment]
Proofreader response

> I removed a lot of the redundancy in the first two chapters already, and have a flow in mind for the third chapter that should smoothly conceptually transition.
As it stands, here is the approach I have been taking for key principals of each chapter:
Chapter 1) WHY to USE Monero (nontechnical, for general audience)
Chapter 2) HOW to USE Monero (nontechnical, for general audience)
~ somebody who has never heard of Monero prior to reading this book should be able to read up to this point and know everything about how to practical use Monero on a day-to-day basis ~
Chapter 3) HOW Monero WORKS (semi-technical, starting to dig into the crypto concepts)

> You can see in my introduction of the second chapter that I use the first paragraph or two to help the reader orient where they are in the book and what they will learn from this chapter. By including the guideposts in each of the first three chapters, referencing the other three chapters, people who are already familiar with using Monero wallet should be able to see clearly that they can skip chapter 2.
I think it might be better to *not* flip the chapters, when I think about it from the perspective of both types of reader.
% Advanced reader - will easily know that they can skip over chapter 2, will not get confused.
% Novice/naive reader - will probably find the book more approachable in the current order, with easy concepts and practical tools before the complicated unnecessary cryptography information. If we switch the chapters, our novice readers may become overwhelmed by not understanding the cryptography details and may give up on Monero before getting to the easy wallet introduction. I like the current order because it allows us to make it very clear that you can use Monero without being a cryptography genius, which is a common misconception that scares a lot of people away.

**Comment by QuickBASIC** [comment]
No, I think it's fine now that I understand the intent. Why/How/What for the chapter order makes a lot of sense now that you put it this way. I know you said that the second chapter was going to be edited, but I was just concerned that even though the topics were not as complex as chapter 3, it was still a bit information dense because it listed all the command line options and started delving into the CLI. 

I'm eager to see the updated chapter, so I can provide feedback though.

**Comment by xmrhaelan** [comment]
Makes sense to me too, although part of me wonders if the How should be at the very end...
