### ISSUE TITLE
What's missing?

### ISSUE THREAD

**Issue by serhack** [monerobook/monerobook#34]
Would you like to contribute to this project?
There are a lot of contents that are missing from the resource.

- Integrate Monero Chapter + OpenAlias (including JSON RPC, the daemon and wallet api, not monero integrations projects)
- Monero subproject: Kovri 
- Monero P2P
- Monero Hard fork / Consensus

**Comment by cryptochangements34** [comment]
Also an in depth explanation of ring signatures and RingCT and a basic note about elliptic curve addition would be nice additions to chapter 6
