### ISSUE TITLE
CH1 Introduction.Ethical discussion

### ISSUE THREAD

**Issue by shmacoshmuesday** [monerobook/monerobook#45]
Can Mastering Monero please not take a stance on 'legal' vs 'illegal'? 

If there is an ethical discussion, maybe we can just remove the words legal and illegal, and mention that people have always and will always do bad things with money. Wars of aggression are funded with every major currency. 

Supporting Monero is not about censoring participants. Monero takes money and transacting out of the hands of those who would wish to have the power to control others property. 

I would love to be able to spot and censor transactions for things I don't like (weapons sold to aggressive countries and world-police types, things like that) but fortunately or unfortunately I won't ever have the power to identify things like that on the monero blockchain, much less censor it even if I could find them.

**Comment by cryptochangements34** [comment]
Personally I would leave out the whole last paragraph of that section. I would just leave it with the sentiment of "money can be used illegally regardless of which currency"
