### ISSUE TITLE
Almost entire paragraph repeated in 1.3.5.

### ISSUE THREAD

**Issue by Domol** [monerobook/monerobook#53]
Hello!
I've just started reading the book and found that text:

`to facilitate illegal activity, which has plagued every currency since the idea of money was conceived thousands of years ago. The scale of illegal transactions conducted using cryptocurrencies is dwarfed by the staggeringly-vast amount of criminal activity that occurs every day denominated in fiat currencies like Euros, Rupees, Yen, or Dollars.`
is repeated two lines below.
Do not know if this is intended but wanted to give heads-up.
Edit:
I am not sure if this is the case but here is PR that removes paragraphs that I think should be replaced by new added in last [commit](https://github.com/monerobook/monerobook/commit/3e9f34fe4a0380f114fcfd0ca56b3c58e97c7e3b#diff-7b76f87d0ff90e4ced53dc3e8845c9ccR179)
PR: https://github.com/monerobook/monerobook/pull/54

**Comment by serhack** [comment]
Ops, I forgot to delete that.
Thanks!
