### ISSUE TITLE
working on a Chinese version

### ISSUE THREAD

**Issue by gzuhlwang** [monerobook/monerobook#56]
Hi, the book is awesome, we are translating the book into a Chinese version, the repo name is [monero_book](https://github.com/YinXinCryp/monero_book).

**Comment by serhack** [comment]
Hi, 

This repo has not been updated and it has a lot of old text.
I have not decided yet in what way we should manage the translations, but I think we should add a folder where users will add translations. Why did not I decide this? I would like to have firstly the resource released in English Language, then we could think about.

Cheers,
SerHack

**Comment by SamsungGalaxyPlayer** [comment]
As @serhack mentioned, please do not begin translating the GitHub content. It is out of date and the translations would be a waste of effort. The book is expected to be published extremely soon (within about a month). We will provide you with some updated content to translate when the English version if finished.

**Comment by gzuhlwang** [comment]
@serhack @SamsungGalaxyPlayer thanks for suggestions, we just finished the draft of some chapters. If changes are not heavily huge, we might as well finish translating the remaining. Look forward to final book.

**Comment by serhack** [comment]
For some chapters like 5th and 6th one the changes are huge! I'll upload the content as soon as the book is released. Thank you for patience.

**Comment by bitOMG** [comment]
感谢这位中国朋友！有中文版那就太好了。

**Comment by gzuhlwang** [comment]
@bitOMG Hi, we will continue translating the remaining parts when the final e-book is available in Jan. 2019.

**Comment by GildedHonour** [comment]
shi pushi chushi kushi
shi-shi, shi-shi. shiii!

I can help you

**Comment by almutsim** [comment]
Hi @gzuhlwang. Thanks a lot for taking this on. Am interested in supporting the effort. What would be a good next step?

**Comment by gzuhlwang** [comment]
@serhack @SamsungGalaxyPlayer hi, thank you guys for you work. Due to the official book available, we will restart the translation and align the [repo's content](https://github.com/YinXinCryp/monero_book) to the first edition. we create an [issue](https://github.com/YinXinCryp/monero_book/issues/4) for tracking.

**Comment by erciccione** [comment]
@gzuhlwang The Monero Localization workgroup doesn't take care of the translation of mastering monero (not yet at least), but please, feel free to contact me for any info/clarification.

**Comment by gzuhlwang** [comment]
@erciccione Absolutely, we will.
