### ISSUE TITLE
Do you accept contributors?

### ISSUE THREAD

**Issue by hokkjoy** [monerobook/monerobook#58]
I just cloned this repository in order to contribute some minor corrections, but it turned out that this isn't the code for the paperback.

Now I realize that the [FFS request](https://forum.getmonero.org/8/funding-required/89797/mastering-monero-ffs) never promised that "Mastering Monero" would be open source.

Regardless, is there a way to get access in order to contribute content?

**Comment by serhack** [comment]
I confirm that Mastering Monero will be open source. As soon as we release the resource in digital version (ePUB and PDF), I'll commit the entire content.

**Comment by pille** [comment]
i'm currently fixing some typos as well. @serhack is that still necessary, or will the final release already be proofread?

**Comment by serhack** [comment]
@pille any help is appreciated!

**Comment by pille** [comment]
@serhack: here it is: #59

**Comment by erciccione** [comment]
@serhack Is this repo synced with the book now? i remember it wasn't the case not long ago.

**Comment by serhack** [comment]
I'll make an announcement when it's synced with book. It's important to release firstly the ebook and free PDF content.

**Comment by erciccione** [comment]
Ok, i think @pille should be noticed of that. He is working on an obsolete version.

**Comment by serhack** [comment]
Part (chapters from 1 to 6, including preface) of this repository has been already synced with book.

**Comment by hokkjoy** [comment]
> It's important to release firstly the ebook and free PDF content.

Why?

The lack of transparency leaves a bitter aftertaste. Personally, I cannot possibly imagine a scenario where the physical book would actually be finished before a digital copy.

If this as about financial objectives, I am sure most would understand as long as you are open about it and nurture proper expectations.

**Comment by serhack** [comment]
> The lack of transparency leaves a bitter aftertaste. Personally, I cannot possibly imagine a scenario where the physical book would actually be finished before a digital copy.

I'm really sorry to hear about this. For several months, me and Mastering Monero team have been working on digital edition which require many many work than the physical one. Given example, think about the ePUB. Formatting it could be a challenge task and for us it was a big one! 

Regarding the reason behind my decision of releasing PDF before the free content on GitHub is pure marketing. However, I think my phrase could be misunderstood, my original idea is releasing all the content at the same time. Then the difference between time of releasing PDF and free content would be very little, in fact we'll announce the news at the same day.

**Comment by hokkjoy** [comment]
I do understand that it is a lot of work and that open communication would allow for potential contributors to see where help is needed and actively provide it.

The [attached mastering-monero-draft](https://github.com/monerobook/monerobook/files/3075582/mastering-monero-draft.zip) would be a primitive ePUB based on the current contents of the "chapters" directory. Simply **rename** it from .zip to .epub.

**Comment by aaronmboyd** [comment]
I've purchased the physical copy from Amazon and finding a few typos and grammatical errors as I read through.

Based on the thread above, I should not submit PRs to this repository then?

**Comment by serhack** [comment]
Why shouldn't you submit the pull request? This issue was created before the digital version release. I can confirm that all the contents on the digital version are uploaded on Github too. 

You're free to submit any pull requests! Thank you in advance

**Comment by nelsonrenan** [comment]
Hi for all. I would like to contribute to the portuguese translation. Is there any work in progress?

**Comment by serhack** [comment]
I am not aware of any translations, except for Chinese one.
