### ISSUE TITLE
chapter 8 missing?

### ISSUE THREAD

**Issue by pille** [monerobook/monerobook#60]
`chapters/8.md` is not available.
this is either a numbering error, or the file is really missing.

**Comment by serhack** [comment]
It's missing. I'm releasing the chapters slowly.

**Comment by pille** [comment]
what's the reason behind this?

**Comment by serhack** [comment]
The free PDF has not been released yet.

**Comment by pille** [comment]
i thought this repo also serves the purpose of creating/releasing it.
