### ISSUE TITLE
Index Error in Equality

### ISSUE THREAD

**Issue by YinXinCryp** [monerobook/monerobook#65]
hi, guys. The original sentence in  5.3.4.3 is "If the equality X==Hs(pV0•R)G+PS0 is true, then that output can be unlocked and spent! ".  Original equality has an index error. the equality possibly should be X == Hs(pV0•R)G+PSi.  please check. thanks.

**Comment by serhack** [comment]
Thank you! For second edition, I'm going to ask some feedbacks to MRL guys before publication.
