### ISSUE TITLE
Chapter 4 v2- Suggested edits

### ISSUE THREAD

**Issue by xmrhaelan** [monerobook/monerobook#66]
Overall this chapter is looking great! Below **in bold** are a few suggested edits:

- [x] 4.2.3- Consider adding this sentence to last paragraph: 

> There are some minor privacy concessions that come into play when using remote nodes, since the node operator is aware of the times and IP addresses from which your device broadcasts transactions or connects for updates. **This could be mitigated by connecting to the node via a VPN or Tor.** The upcoming Kovri privacy technology will significantly mitigate these.... 

- [x] 4.3.4-Consider adding a comparison to Gold in last paragraph:

> The annual supply increase from Monero's 0.6 XMR tail emission is less than 1% per year. **This is comparable to the annual gold supply increase globally, which in modern civilization has historically been the purest and most stable form of money.**

- [x] 4.4.1.2- **Fix the heading**

- [x] 4.4.3.2- Fourth paragraph, fix misspelling of amateur:

> It would be difficult to exert this influence over a global collection of **amateur** miners, and...

- [x] 4.4.3.3- A suggested update to the last paragraph:

> For the time being, it appears that the Monero network has successfully mitigated the unexpected ASIC threat. To **continue discouraging ASICs**, Monero now slightly changes the mining algorithm at each network update. **They are also exploring entirely new algorithms to safeguard the network from ASICs long term.** Since Monero carries out routine hard forks every 6 months, this should ~~**permanently**~~ disincentivize attempts to produce Monero ASICs, since each expensive and lengthy redesign would be promptly rendered obsolete.

**Comment by aaronmboyd** [comment]
_Re: Comparison to gold._
While it may give people new to blockchain a clear anchor point for understanding, I'm not sure we want to send people down the path of simple comparisons with asset-backed traditional financial systems. Additionally, the way your suggestion is written _almost_ makes it seem like the tail emission was set based on a real-world analogue.

**Comment by serhack** [comment]
> This could be mitigated by connecting to the node via a VPN or Tor. The upcoming Kovri privacy technology will significantly mitigate these....

Could we improve this phrase since Kovri is practically a deceased project? "Connecting to the node via a VPN or TOR will partially mitigate these.."

I agree with @aaronmboyd regarding the comparison to gold.

**Comment by xmrhaelan** [comment]
> _Re: Comparison to gold._
> While it may give people new to blockchain a clear anchor point for understanding, I'm not sure we want to send people down the path of simple comparisons with asset-backed traditional financial systems. Additionally, the way your suggestion is written _almost_ makes it seem like the tail emission was set based on a real-world analogue.

There are several simple comparisons throughout this book, that give people clear anchor points for understanding. I think each of them enhances the readability of the book and the comprehension of the reader. I see your point about the perceived intent of tail emission though. What if we used this wording?

> The annual supply increase from Monero's 0.6 XMR tail emission is less than 1% per year. **While developers created tail emission to incentivize miners long-term, a neat by product is its easy comparison to to asset backed financial systems. The tail emission rate of supply increase** is comparable to the annual gold supply increase globally, which in modern civilization has historically been the purest and most stable form of money.

^@serhack for the first edition I had also added a piece somewhere about how tail emission mimics stable, predictable inflation. Is that still in this book? If so perhaps we could add it here as well.

**Comment by xmrhaelan** [comment]
> > This could be mitigated by connecting to the node via a VPN or Tor. The upcoming Kovri privacy technology will significantly mitigate these....
> 
> Could we improve this phrase since Kovri is practically a deceased project? "Connecting to the node via a VPN or TOR will partially mitigate these.."
Yeah I was wondering why Kovri is still in this book. I assumed you knew something I didn't... :) I think your correction works great.

**Comment by aaronmboyd** [comment]
@xmrhaelan I get what you're saying and it might just be more my personal preference of how I present blockchain and cryptocurrencies to people in general. I'm not on the original authoring team and just amended a few typos and algebra errors, so I'll leave the overall tone to the authors.

However, if it were me - I wouldn't mention asset-backed financial systems at all. I don't really agree with the "digital gold" narrative in the crypto world - and it's somewhat over-simplifying for a book that is already quite technical and detailed. I think it's better to demonstrate how cryptocurrencies _differ_ from hard assets, not mirror their features.

Finally, 
> has historically been the purest and most stable form of money.

This is somewhat subjective. Isn't this why we are all here to begin with?

Splitting hairs I know, but just putting in my two cents as a Monero advocate.

**Comment by xmrhaelan** [comment]
>However, if it were me - I wouldn't mention asset-backed financial systems at all. I don't really agree with the "digital gold" narrative in the crypto world - and it's somewhat over-simplifying for a book that is already quite technical and detailed.

Well, whether we like it or not, this is the paradigm that people have been most familiar with for most of their lives. To draw parallels whenever possible will surely increase their comprehension of the many different aspects/features of Monero, of which tail emission is just one. 

>I think it’s better to demonstrate how cryptocurrencies differ from hard assets, not mirror their features.

I think that’s what the rest of the book is about ;)

>This is somewhat subjective. 

I don’t think it is. Throughout modern civilization, gold has survived as the best form of money and has outlived every single fiat currency that was ever formed. Ultimately all fiat currencies have failed. Prior to gold, people traded with stones, shells, cattle, etc. Gold was the first form of money that had all of the key features: durable, portable, divisible, fungible, etc.... and it’s still around.

This was all before the invention of Bitcoin of course. Then Monero came along and solved the fungibility problem of Bitcoin. Even still, gold has survived the test of time (a few thousand years) and is the most objective, long-term example of pure money. Just as Monero, gold is more than just a store of value. It’s historical use as real money is precisely why it’s valuable.

My goal in the suggested section was not necessarily to compare Monero the coin to gold, but to compare Monero’s feature of tail emission to the global annual mining of gold and support the idea that such a low rate of emission has worked fine for the precious metal that has stood up to the test of time as real money. “If it’s good enough for stable gold supply that has survived thousands of years, it’s good enough for Monero’s supply” If there’s a better way to word this to get that goal across, I am open to suggestions.
