### ISSUE TITLE
Chapter 5 v2- Suggested edits

### ISSUE THREAD

**Issue by xmrhaelan** [monerobook/monerobook#67]
I really enjoyed reading this chapter. Below are some suggested edits for consideration:

- [x] 5.2.2- third paragraph word choice. Replace word build with built.

> ...which employs a special CryptoNote hash algorithm, which is **built** on the Keccak...

- [x] 5.2.3- **Fix heading. Make bold.**

- [x] 5.3.2.2- fourth paragraph, reword:

> For example, consider the ~~the~~ ~~**main**~~ **Monero General Fund** donation address:

- [x] 5.3.2.2- Consider adding paragraph before concluding paragaph:

> **The view-only wallet feature of Monero may also prove to be Monero's protection against regulation that would attempt to ban Monero in certain jurisdictions. Since individual Monero users can _choose to share_ their view-keys, they could choose to provide them to auditors to verify their funds. This would be a reasonable approach to appeasing auditors and as a result, relinquish fears that Monero could not work within the paradigms of existing financial structures.**

- [x] 5.3.2.2- Last paragraph. I do not have suggested wording, but isn't their a workaround for view-only wallets not showing outgoing transactions, via sharing key images? If information on that were included here I think it would complete this section.

- [x] 5.3.4- Second paragaph. Swap words: to link > link to

>  ....so nobody can **link to** those transactions from analyzing the blockchain (including the spenders). However, this....

- [x] 5.3.4.3.3 Second paragraph. Pick one of the words, its or the. I suggest its.

> ....the wallet checks calculations based on its ~~the~~ public view key and public spend key.

- [x] 5.4.3- Third to last paragaph. This doesn't make sense to me and I'm not sure how to properly suggest an alternative.

> Nobody can ascertain which commitment hides your true key, but everybody can mathematically verify for themselves that:

**the sender knew one of the private keys represented by the public keys the key image was computed correctly**

Trying saying this sentence^ out loud, then consider rewriting in a way that makes more sense.

- [x] 5.4.4- Consider editing:

> If you want to venture even further into the calculations behind these technologies, check out **'Zero to Monero', by Alonso, K.M. & Koe.** This **book** is a highly-technical mathematical tour that is also available as a free community-funded PDF.

- [x] 5.5.3.2- Second paragraph. Delete "a"

> To avoid these issues, Monero uses a dynamic block size mechanism that allows the miners to use ~~**a**~~ larger blocks to accommodate increased traffic.

- [x] 5.5.3.3- Third paragaph. Delete "in", add "s" to transaction.

> Fees are calculated by the weight ~~**in**~~ of the transaction in kB. Larger (“heavier”) transaction**s** incur a higher fee. 

- [x] Add a 5.6 Conclusion

> **As you can see, Monero uses several highly sophisticated encryption protocols to secure its network and adhere to the fundamental principles of privacy and decentralization. With the help of the Monero Research Lab and various auditing agencies, Monero will continue to identify and validate cutting edge encryption technology to make the technology as fast, secure, private, and efficient as possible.**

>**One of the key features of money is the feature known as fungibility. Fungibility means that one piece of value is equal to another piece of value of the same amount. One ounce of gold equals one ounce of gold. Or in our case, one moneroj equals one moneroj. _The encryption protocols used by Monero make it fungible and allow it to reach its goal of being true, digital money._**

>**Cryptocurrencies that are transparent at their base layer do not have these encryption layers in place and as a result, are not fungible. A coin that can be traced to the dark net will be tainted and coins that are newly minted or sold on auction by law enforcement might be sold at a premium. So in the case of transparent cryptocurrencies, one coin does not equal the same value as another coin of the same amount. They are not fungible. This is truly problematic in the goal of being digital money.**

>**So beyond maintaining good security, privacy, and decentralization through Monero's sophisticated encryption protocols, it also ensures fungibility, an essential component of sound money.**

**Comment by xmrhaelan** [comment]
Also just noticed an error. When creating a view-only tutorial I copied the Monero general fund address that is on section 5.3.2.2 into the GUI wallet restore and it was read as incorrect. I then copied the Monero general fund address that is listed on the CCS website and it worked. It appears the address that you have listed here might have a missing digit or something. This is the correct address from the CCS website: 44AFFq5kSiGBoZ4NMDwYtN18obc8AemS33DBLWs3H7otXft3XjrpDtQGv7SqSsaBYBb98uNbr2VBBEt7f2wfn3RVGQBEP3A

**Comment by serhack** [comment]
> The view-only wallet feature of Monero may also prove to be Monero's protection against regulation that would attempt to ban Monero in certain jurisdictions. Since individual Monero users can choose to share their **private view-key**, they could choose to provide it to auditors to verify their funds. This would be a reasonable approach to appeasing auditors and as a result, relinquish fears that Monero could not work within the paradigms of existing financial structures.

**Comment by serhack** [comment]
> 5.4.3- Third to last paragaph. This doesn't make sense to me and I'm not sure how to properly suggest an alternative.

Regarding this, I missed a bullet point.

**Comment by serhack** [comment]
>  Add a 5.6 Conclusion

Regarding its content, it's fantastic. You did a good work! Honestly I would not identify this as a conclusion (except for the last paragraph), but as a subsection with the title "Fungibility". I'm not sure where we should add this. I'd like to get people read this subsection.

**Comment by xmrhaelan** [comment]
> > The view-only wallet feature of Monero may also prove to be Monero's protection against regulation that would attempt to ban Monero in certain jurisdictions. Since individual Monero users can choose to share their **private view-key**, they could choose to provide it to auditors to verify their funds. This would be a reasonable approach to appeasing auditors and as a result, relinquish fears that Monero 
could not work within the paradigms of existing financial structures.

Good catch!

**Comment by serhack** [comment]
:)

**Comment by xmrhaelan** [comment]
> > Add a 5.6 Conclusion
> 
> Regarding its content, it's fantastic. You did a good work! Honestly I would not identify this as a conclusion (except for the last paragraph), but as a subsection with the title "Fungibility". I'm not sure where we should add this. I'd like to get people read this subsection.

Thank you. I think changing the title to Fungibility would be fine, but I would argue it still belongs in this chapter. The fungibility of Monero is directly linked to the success of its encryption layers.
