### ISSUE TITLE
Chapter 6 v2- Suggested Edits

### ISSUE THREAD

**Issue by xmrhaelan** [monerobook/monerobook#68]
Having been involved in the community pretty heavily over the past year and a half, I enjoyed reading and contributing to this chapter. Here are my suggested edits:

- [x] 6.1.2- Add to first paragraph-

> At the time of writing, more than 500 people have contributed code, including 200 in the last year. **Among all cryptocurrencies this number of contributors is led only by Bitcoin and Ethereum.** Monero has adopted an un-governance...

- [x] MRL has a new URL: https://web.getmonero.org/resources/research-lab/. The current one listed has a redirect.

- [x] Expand the Workgroups paragraph:

> The Monero Workgroups are collaborations formed to join people around unique goals. This allows small teams of individuals to connect and tackle specific tasks. For example, the Monero Hardware Workgroup is well underway on its mission to build the first open-source community-driven hardware wallet. **Monero Localizations Workgroup has translated Monero code and content into dozens of languages. Monero Outreach is a workgroup that is working on increasing adoption and awareness of Monero.** Another instance was the Monero Integrations Workgroup, which developed open-source payment gateways. 

>**Other workgroups plan events, craft kits for Meetups, or help users with software issues. Anyone can get involved in a Monero workgroup, and you are invited to do so! You can get started with these resources:**

>**1. See which workgroups are active on Taiga: https://taiga.getmonero.org/discover**
>**2. Join the discussion on IRC #monero-community and find out where your skills and passions might be best suited to help.**

- [x] 6.2.4- Add to first paragraph:

> Many different repositories are hosted at the Monero Project **and on** GitHub. **In fact, there are over 23 repositories in the Monero Ecosystem and 340 repositories on the Monero topic.** Several of them house components that we've already discussed in Mastering Monero, for example:

- [x] **Add 6.2.5- Monero-announce Mailing List**

> **There is a mailing list that sends important announcements about the Monero software and network. Anyone who is interested in being involved in the Monero community or staying informed of its updates is welcome to subscribe to the mailing list here: https://lists.getmonero.org/postorius/lists/monero-announce.lists.getmonero.org/**

**Comment by serhack** [comment]
> Monero Localizations Workgroup has translated Monero code and content into dozens of languages. Monero Outreach is a workgroup that is working on increasing adoption and awareness of Monero.

I would not mention each workgroup and their mission/goals. 

> You can get started with these resources:

There're so many things to mention here to getting started into community!

**Comment by xmrhaelan** [comment]
>I would not mention each workgroup and their mission/goals.

These are just two more examples out of the many that exist, but if you feel that it’s too many, please at least leave the Localizations workgroup here.
