### ISSUE TITLE
Chapter 8 v2- Add View-only wallet tutorial.

### ISSUE THREAD

**Issue by xmrhaelan** [monerobook/monerobook#70]
This chapter is a good start, and feels incomplete. I think one thing that could be added would be: 

**How to add a view-only wallet**
This tutorial assumes you have already setup a paper/cold storage wallet, and are now ready to create a "view-only" wallet in the GUI.

1. Launch Monero GUI program.
2. At landing screen, select, "Restore wallet from keys or mnemonic seed."
3. Edit your preferred "Wallet Name" and "Wallet Location"
4. Select the button "Restore from Keys"
5. Enter the Public Address for the paper/cold storage wallet you created.
6. Enter the Private View Key for the paper/cold storage wallet you created.
7. Leave the Private Spend Key field blank!
8. Enter your preferred Restore hieght or creation date. Hit next button.
9. On the next screen enter a strong password. Hit next button.
10. On the next screen select whether you want to connect via local node (recommended) or a remote node. If local, select the folder that contains your copy of the blockchain.
11. On the last screen, confirm the wallet details are correct and Open the view-only wallet!

Now you can view and confirm transactions that you've sent to your paper/cold storage wallet!

If you'd like to do a test run to get familiar with the process, you may like to follow the above steps with the Monero General Fund wallet information:

Public Wallet Address: 44AFFq5kSiGBoZ4NMDwYtN18obc8AemS33DBLWs3H7otXft3XjrpDtQGv7SqSsaBYBb98uNbr2VBBEt7f2wfn3RVGQBEP3A

Private View Key: f359631075708155cc3d92a32b75a7d02a5dcf27756707b47a2b31b21c389501

**Comment by serhack** [comment]
Done.

**Comment by xmrhaelan** [comment]
Should I ask more people to weigh in on this chapter and suggest tutorials?

**Comment by serhack** [comment]
@xmrhaelan At the moment, you should not since this will be added to Appendix B in the second edition. If it's needed, we could have a big "appendix" called "Tutorials" where we will put all the tutorials. I'd like to avoid that since GUI interface can change in a day and it'll be hard to maintain all those tutorials.
